#  NotCredits plugin
#     By NotMarra


#Set which language the plugin should use
#All available languages can be found in the lang folder
#You can create your own lang file, just duplicate en.yml and rename it
#Available lang files: en, cz, zhcn.yml, ptbr
#Language from Contributors: zhcn.yml (Simplified Chinese by SnowCutieOwO), ptbr (Portuguese (Brazil) by NetoSantoos78)
lang: "en"

data:
  #Set the type of the database
  #Available types: SQLite, MySQL, PostgreSQL, MariaDB
  type: "SQLite"
  #What will be the name of the file with the saved data (only works with SQLite and H2)
  file: "data"
  #What will be the name of the table with the saved data (only works with MySQL, PostgreSQL, MariaDB)
  table: 'NotCredits'

  #If data type is set to MySQL, PostgreSQL or MariaDB, fill in the following fields
  mysql:
    host: ''
    port: 3306
    username: ''
    database: ''
    password: ''

# The default credits balance of a first-time joiner.
default_balance: 0

#Set true if you want decimal numbers
balance_decimal: false

#How the numbers will be formatted (#.## means the number will look like this: 1.25)
#Only works if "balance_decimal" is set to true
balance_format: '#.##'

#Set true if you want to use Vault
vault: false

#If top placeholder is empty, it will show this message
placeholder_no_data: "NaN"

#DO NOT CHANGE THIS
ver: 1