#  NotCredits plugin
#     By NotMarra


#Set which language the plugin should use
#All available languages can be found in the lang folder
#You can create your own lang file, just duplicate en.yml and rename it
#Available lang files: en, cz
lang: "en"

#DO NOT CHANGE THIS
ver: 1
