#  NotCredits plugin
#     By NotMarra


#Set which language the plugin should use
#All available languages can be found in the lang folder
#You can create your own lang file, just duplicate en.yml and rename it
#Available lang files: en, cz
lang: "en"

data:
  #Style how to save data
  #Now its only possible to use MySQL and SQLite only:
  type: 'SQLite'
  #What will be the name of the file with the saved data (only works with SQLite)
  file: 'data.db'
  #What will be the name of the table with the saved data (works on both)
  table: 'NotCredits'

  #If data is set to MySQL, enter the login information from MySQL
  mysql:
    hostname: ''
    port: '3306'
    username: ''
    database: ''
    password: ''
    url: 'jdbc:mysql://%hostname%:%port%/%database%'


# The default credits balance of a first-time joiner.
default_balance: 0

#Set true if you want decimal numbers
balance_decimal: false

#How the numbers will be formatted (#.## means the number will look like this 1.25)
#Only works if "balance_decimal" is set to true
balance_format: '#.##'

#If this is set to true, the plugin will create an economy for the vault.
#The Vault plugin is required on the server!
vault: false