name: NotCredits
version: '${project.version}'
main: com.notmarra.notcredits.NotCredits
api-version: '1.21.4'

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false