name: NotCredits
version: ${project.version}
main: com.notmarra.notcredits.Notcredits
api-version: 1.19
authors: [ NotMarra ]
description: Economy plugin
website: www.notmarra.com
softdepend: [PlaceholderAPI, Vault]
commands:
  credits:
    description: Base command for NotCredits
    usage: /<command>
    aliases: [nc, notcredits]