name: NotCredits
version: '1.0.4-SNAPSHOT'
main: me.notmarra.notcredits.Notcredits
api-version: 1.19
authors: [ NotMarra ]
description: Economy plugin
website: www.notstudio.cz
softdepend: [PlaceholderAPI, Vault]
commands:
  credits:
    description: base command of plugin
    usage: /<command>